richard:
  info:
    version: 1.0.0
    base-package: com.richard.bookstore

spring:
  application:
    name: bookstore-server
  datasource:
    url: jdbc:mysql://localhost:3306/richard-bookstore?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    id-type: AUTO
    logic-delete-value: 1
    logic-not-delete-value: 0
  banner: false
  mapper-locations: classpath:com/richard/bookstore/mapper/xml/*.xml

